# Site settings
baseurl = "http://blog.vladimirm.com/"
languageCode = "en-us"
title = "Vladimir Momirov"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-18578779-3"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Vladimir Momirov"
	description = "Personal blog about web development"
	bio = "Programmer"
	# Enter optionally your twitter account
	twitter = "svemirov"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "A passionate web developer."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    github   = "https://github.com/momirov"
    twitter  = "https://twitter.com/svemirov"
    email    = "mailto:&#98;&#x6c;&#111;&#103;&#64;&#x76;&#108;&#97;&#x64;&#x69;&#x6d;&#105;&#x72;&#x6d;&#46;&#99;&#x6f;&#x6d;"
[permalinks]
    post = "/:year/:month/:title"
